language: node_js
sudo: false
node_js:
  - "4"
before_install:
  - npm install -g Financial-Times/origami-build-tools#node4
  - obt install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - obt test
  - obt verify
